### ISSUE TITLE
Manuelle Eingabe von existierenden Klassen nicht möglich

### ISSUE THREAD

**Issue by ngdot** [Craffft/css-style-selector-bundle#10]
Es ist nicht möglich Klassen die bereits angelegt wurden, selbst in das Klassenfeld zu schreiben. Nach dem speichern ist die Klasse einfach weg.

Als Entwickler wäre es außerdem von Vorteil die vorher definierten Klassen auch selbst schreiben zu können.Außerdem wäre es cool, wenn das Select Feld auch nach dem eig. Value also der Klasse suchen würde.

**Comment by ngdot** [comment]
Ist wahrscheinlich der gleiche Fehler wie #4

**Comment by iCodr8** [comment]
> Es ist nicht möglich Klassen die bereits angelegt wurden, selbst in das Klassenfeld zu schreiben. Nach dem speichern ist die Klasse einfach weg.

Das ist nicht möglich, weil in diesem Moment verhält es sich so, als würde man den Wert im Select Feld entfernt haben. Dadurch wird der Wert dann im Klassen Feld entfernt. Die Funktionalität ist hier korrekt.

> Als Entwickler wäre es außerdem von Vorteil die vorher definierten Klassen auch selbst schreiben zu können.Außerdem wäre es cool, wenn das Select Feld auch nach dem eig. Value also der Klasse suchen würde.

Nach dem Value zu suchen, wäre eine gute Sache, geht aber leider nicht, da das Feld nur die sichtbaren Werte in der Liste filtern kann.

**Comment by ngdot** [comment]
Okay, danke für dein Feedback!

Wie wäre es wenn man die css klasse in den Namen mit einbaut? Zum Beispiel in Klammern hinten ran?

Von meinem iPhone gesendet

**Comment by iCodr8** [comment]
Ja, das wäre eine Option. Wenn Du möchtest, kannst Du uns einen Pull-Request stellen.

**Comment by ngdot** [comment]
Habe ich erledigt :) Checkt das mal ab!

**Comment by iCodr8** [comment]
ok
