### ISSUE TITLE
Kopieren unter Contao 4.4.18

### ISSUE THREAD

**Issue by ngdot** [Craffft/css-style-selector-bundle#9]
Leider ist es nicht möglich einen, oder mehrere CSS-Stil zu kopieren.
Nach dem klick auf "CSS-Stil duplizieren" lädt er neu, aber ich bekomme die "Insert-Maske" nicht.
Gleiches Spiel wenn man mehrere duplizieren möchte.

**Comment by iCodr8** [comment]
Bitte mal testen, ob es mit dem Branch von #12 funktioniert.

**Comment by ngdot** [comment]
Hm… funktioniert nur bedingt. Bei Klick auf "+" komme ich direkt in die Eingabemaske und kann die Kopie umbenennen & speichern. Wenn ich aber mehrere kopieren will, funktioniert es nicht. Mich wundert allerdings warum das so ist, eig. ist `'href' => 'act=paste&amp;mode=copy',` korrekt und nicht `'href' => 'act=copy',`.

**Comment by iCodr8** [comment]
`'href' => 'act=paste&amp;mode=copy',` das hatten wir vorher. Dann hat die Änderung also nichts gebracht.

**Comment by fritzmg** [comment]
Ja, das nervt mich auch schon länger 😁. Als Workaround editiere ich einen Beitrag immer und benutze "Speichern & duplizieren"; das funktioniert.

**Comment by iCodr8** [comment]
Das ist die Lösung:

```
'href' => 'act=copy'
```

Ich bau es ein.
